### ISSUE TITLE
DDG DMP Consent eDA Profile / DDG DMP Consent Registry Profile

### ISSUE THREAD

**Issue by marloverket** [michaelonken/dmp_diabetes#18]
Please add SNOMED code: 414925007

**Comment by michaelonken** [comment]
For reference: https://browser.ihtsdotools.org/?perspective=full&conceptId1=414925007&edition=MAIN/2022-03-31&release=&languages=en

**Comment by michaelonken** [comment]
Replaced LOINC 59284-0 (Consent Document) with Snomed CT 414925007 (Obtaining Consent) in commit 5bc86050074fa78fb3ba5ffda075fb8ce2c377fd.
